# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - func-starter-sample

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
            npm install
            npm run build --if-present
            popd
  
      - name: 'Run Docker Compose'
        run: |
            docker compose -f ./docker/docker-compose.yml up -d --wait

      - name: 'Show Docker Compose log'
        run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
            cd ./docker
            docker compose logs
            popd

      - name: 'Wait for DB to be ready'
        run: |
            host="localhost"
            dbUser="root"
            dbPass="root"
            until mysql --host=$host --user=$dbUser --password=$dbPass --protocol=TCP -e "SELECT 1"; do
              echo "Waiting for DB to start..."
              sleep 5
            done

      - name: 'Run tests'
        run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
            npm run test --if-present
            popd

      # これは、Azure Functionsのリソースが作成されていることが前提
      # - name: 'Run Azure Functions Action'
      #   uses: Azure/functions-action@v1
      #   id: fa
      #   with:
      #     app-name: 'func-starter-sample'
      #     slot-name: 'Production'
      #     package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      #     # set the secret key to your Azure function.
      #     # you can get the secret key after setting cicd in your Azure function.
      #     # once you set the cicd, you can get the secret key in Github Setting pages.
      #     publish-profile: ${{ secrets.xxx }}
